POST http://localhost:8080/cards/charges
Content-Type: application/json
#Accept: application/binary-data
Accept: application/json

{
  "amount": 20.0,
  "currencyCode": "PLN",
  "cardNumber": "1234567890123",
  "cardVerificationCode": "123",
  "cardExpirationDate": "2024-01-01"

}

###

GET http://localhost:8080/cards/charges/72efb983-30c8-4a22-9d0a-01cb5c029404
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/cards/charges
Content-Type: application/json
Accept: application/json
